version: '3'

services:
###> doctrine/doctrine-bundle ###
  apps:
    container_name: fiainanabediabe
    build:
      context: docker/app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/fiainanabediabe:rw+
      - ./docker/apache_conf:/etc/apache2/sites-enabled

  mailer:
    container_name: fbdb_mailer
    image: schickling/mailcatcher
    ports:
      - "8082:1025"
      - "8083:1080"

  database:
    image: mysql:latest
    container_name: fbdb_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: julkwel
      MYSQL_DATABASE: fiainanabediabe
      MYSQL_USER: fiainanabediabe
      MYSQL_PASSWORD: fiainanabediabe@db202e
    volumes:
      - "$PWD/data:/var/lib/mysql:rw"
